// HOTEL LOGIN
export const HOTEL_LOGIN_REQUEST = 'HOTEL_LOGIN_REQUEST';
export const HOTEL_LOGIN_SUCCESS = 'HOTEL_LOGIN_SUCCESS';
export const HOTEL_LOGIN_ERROR = 'HOTEL_LOGIN_ERROR';

// LOGOUT
export const LOGOUT_HOTEL_USER = 'LOGOUT_HOTEL_USER';

export const STORE_NAME_PASS = 'STORE_NAME_PASS';
