// ADD PRODUCT

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

// ADD MEDIA    

export const ADD_PRODUCT_MEDIA_REQUEST = "ADD_PRODUCT_MEDIA_REQUEST";
export const ADD_PRODUCT_MEDIA_SUCCESS = "ADD_PRODUCT_MEDIA_SUCCESS";
export const ADD_PRODUCT_MEDIA_ERROR = "ADD_PRODUCT_MEDIA_ERROR";

