// ADD PRODUCT

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

// ADD MEDIA    

export const ADD_PRODUCT_MEDIA_REQUEST = "ADD_PRODUCT_MEDIA_REQUEST";
export const ADD_PRODUCT_MEDIA_SUCCESS = "ADD_PRODUCT_MEDIA_SUCCESS";
export const ADD_PRODUCT_MEDIA_ERROR = "ADD_PRODUCT_MEDIA_ERROR";

// GET ALL DATA

export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR";

// GET SINGLE DATA

export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";